### ISSUE TITLE
Not working on recent versions of imlib

### ISSUE THREAD

**Issue by Neo-Oli** [gawen947/imlib2-webp#8]
Hey, I have a hard time getting this to work on imlib2 1.10.0.  First problem seem to be that `imlib2-config` was dropped a few versions back. But even working around that by manually setting the Version in the Makefile now leads to errors when used with `imlib2_view` or `feh` (the same errors as when imlib2-webp isn't installed at all). Any ideas what the problems could be?

**Comment by cobaltdr** [comment]
Hello. Came across the same problem, was hoping for a solution.

Reaseach shows:

New versions of imlib2 (I have 1.10.0) support webp if build with the configure flag --with-webp

Making this loader no longer required.

Somewhat hacky, but I managed to build a version on homebrew from source with:

./configure --prefix=/usr/local/Cellar/imlib2/source/imlib2-1.10.0 --libdir=/usr/local/Cellar/imlib2/1.10.0/lib --enable-amd64=no --without-heif --without-id3 --without-j2k --without-jxl --with-webp

make

make install

I suspect a similar approach will work on *NIX with the correct path subtitutes.

My usecase is also to use feh, and I confirm it loads webp fine after this.

**Comment by Neo-Oli** [comment]
> New versions of imlib2 (I have 1.10.0) support webp if build with the configure flag --with-webp. 

@cobaltdr Oh I see. I just figured out that my distributions already ship imlib with webp support. Installing this package now actually breaks webp support because it breaks `webp.so`. Simply removing this and reinstalling imlib2 solves my webp issues. Maybe this repository should be marked obsolete in the README.

**Comment by marhu98** [comment]
There is no configure file in the repo. How are we supposed to run ./configure?

**Comment by gawen947** [comment]
Sorry I was not really available the last few weeks, and I did not see the issue because FreeBSD still has the older version of Imlib2 in its packages.

Anyway imlib2-config was used as a placeholder for systems that did not have pkg-config. Now that pkg-config is ubiquitous and imlib2-config has been deprecated, I just patched the code to use pkg-config instead. But I think we should be able to use both.

It's true that newer versions of Imlib2 support WebP by default. It even supports animation now which this version does not support (yet). However this repo is not obsolete as I still use it (and try to update it) instead of the official version, and try to keep it compatible with older versions of WebP and Imlib2.

@marhu98 the configure file referred to in the comment was in imlib2 source code, not this repo.
